### PR TITLE
Issue #1: Setup requirements

### LINKED ISSUE #1: Add loadbalancer support
See https://github.com/vsk8s/k8router/issues/5

Add system support for this

### PR DESCRIPTION
**Pull request by F1rst-Unicorn**
Install ipvsadm
Activate conntrack for ipvs

Closes #1

### CODE REVIEW

**Comment by uubk** [comment]
If this does not install ipvsadm - then where does that come from and why should we enable it's connection tracking feature here?

**Comment by F1rst-Unicorn** [comment]
As ipvsadm will be necessary dependency once the other PR is merged, it's better listed as debian-package dependency than loosely tied to it over this ansible role. The sysctl flag is set here because I didn't think of it as a package responsibility. Is it common practice in debian to also deliver the sysctl file as package content?

**Comment by uubk** [comment]
It depends. Generally, a package should work after installation and since this will not work without the flag, I take [this](https://lists.debian.org/debian-devel/2017/04/msg00226.html) discussion to mean that you can and should drop a file into `/etc/sysctl.d` as a package.

**Comment by F1rst-Unicorn** [comment]
Will be moved to debian package

**Pull request closed without merging**
